language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
env:
  global:
    - CI_TEST=no-lint
matrix:
  include:
    - node_js: "9"
      script: npm run lint
      env:
        - CI_TEST=lint-only
cache:
  directories:
    - node_modules
